### PR TITLE
Fixed “Use Legacy Swift Language Version”

### PR DESCRIPTION
**Pull request by ConradoMateu**
I had this problem when I wanted to build for testing (⇧+⌘+U)

screen shot 2017-02-05 at 19 30 54

I solved it by adding this part of code to the Podfile:

`post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
  end`

Hope it helps

### CODE REVIEW

**Comment by pedrovgs** [comment]
@Serchinastico do you know if this could be related to the Xcode version?

**Comment by Serchinastico** [comment]
It could be, I tried to reproduce the error but I've been unable so far. As far as I know, SwiftCheck supports Swift 3 from v0.7, have you tried removing your pods and `pod install`ing again? what's your XCode version?

**Comment by ConradoMateu** [comment]
I have xcode 8.2.1, and I have tried to remove pods and then install again but the error is still there.
And the SwiftCheck installed version is 0.7.1 .
Don't know what is causing this problem.

**Comment by pedrovgs** [comment]
Ok, thanks for your help @ConradoMateu. I'm merging this PR :)

**Comment by Serchinastico** [comment]
Just to keep you all in sync, we just realized your version of Cocoapods is quite old, we are `pod install`ing on top of that to update the Podfile.lock. If you update your version you shouldn't see that error anymore. 
We will keep your PR merged, though, so that others don't find the same problem even if their Cocoapods version is outdated.

Thank you again for your time and code!

**Comment by ConradoMateu** [comment]
I didn't realize that my pod version was outdated I will install a newer version, thank you for the merge  :)

**Pull request merged**
